[package]
name = "rpc-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rpc
jsonrpsee = { version = "^0.16", features = ["full"] }
eyre = "0.6.5"
thiserror = "1.0.26"
dotenv = "0.15.0"
tokio = { version = "1.8.1", features = ["full"] }
ezkl = { git = "https://github.com/zkonduit/ezkl.git" }

